#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

docker build -t buildkernel_astro:dev --target dev .

docker run --rm -it \
  --mount "type=bind,src=$PWD,dst=/work" \
  buildkernel_astro:dev \
  "${@-bash}"
