#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/../kernel"

ARCH=arm64
PATH=$PATH:/work/kernel/tools
export ANDROID_MAJOR_VERSION ARCH PATH PLATFORM_VERSION

CC=/opt/clang/bin/clang
CLANG_TRIPLE=/opt/clang/bin/aarch64-linux-gnu-
CROSS_COMPILE=/opt/clang/bin/aarch64-linux-android-
export CC CLANG_TRIPLE CROSS_COMPILE

mkdir -p out/

make -C $(pwd) \
  O=$(pwd)/out \
  ${KERNEL_MAKE_ENV-} \
  CLANG_TRIPLE=$CLANG_TRIPLE \
  ${1:-k6873v1_64_defconfig}

make -C $(pwd) \
  O=$(pwd)/out \
  ${KERNEL_MAKE_ENV-} \
  CLANG_TRIPLE=$CLANG_TRIPLE \
  menuconfig

# copy defconfig out
cp -f out/.config ../out/defconfig
